SCRUM-55--lastEvaluated-Key
aws-educate-tw/aws-educate-tpet-backend pull request #42
Opened 2024-07-25 01:39 UTC by Rich627

2024-07-25 14:50 UTC, sh1un commented
Hi @Rich627,

此 PR 我剛剛測試了，在 preview 環境還有 local-env 環境都會遇到 500 Error，另外程式碼內的註解使用英文比較霸氣


## issues

- [ ] 1. Preview Env (us-west-1) - 500 Error
  - [Logs:](https://us-west-1.console.aws.amazon.com/cloudwatch/home?region=us-west-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fpreview-file_service-list_files-ucaa/log-events/2024$252F07$252F25$252F$255B$2524LATEST$255D40a4194e8f234a098d96e2d2b84d55fb)
    ```shell
    RequestId: 2357defb-ff7d-47bf-88a8-54c4d1140997 Error: fork/exec /lambda-entrypoint.sh: exec format error
    Runtime.InvalidEntrypoint
    ```

    **猜測原因:**
    
    - 這個應該是因為 GitHub Actions 的 Ubuntu 他不是 arm64 架構的，所以你本地開發時可以用 arm64，但是推上來時，由於是 GitHub Actions 的虛擬機會幫你 Build Image，所以推上來的 Docker Image 需要保持 x86_64


- [ ] 2. Local-dev (us-west-2) Env - 500 Error
  * [Logs](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252Flocal-dev-file_service-list_files-izpy/log-events/2024$252F07$252F25$252F$255B$2524LATEST$255D69de3b04bcf447e5936a40d77993c40d):
     ```shell
    Unknown parameter in input: "ScanIndexForward", must be one of: TableName, IndexName, AttributesToGet, Limit, Select, ScanFilter, ConditionalOperator, ExclusiveStartKey, ReturnConsumedCapacity, TotalSegments, Segment, ProjectionExpression, FilterExpression, ExpressionAttributeNames, ExpressionAttributeValues, ConsistentRead
    Traceback (most recent call last):
      File "/var/task/lambda_function.py", line 108, in lambda_handler
        response = table.scan(**query_kwargs)
      File "/var/lang/lib/python3.11/site-packages/boto3/resources/factory.py", line 581, in do_action
        response = action(self, *args, **kwargs)
      File "/var/lang/lib/python3.11/site-packages/boto3/resources/action.py", line 88, in __call__
        response = getattr(parent.meta.client, operation_name)(*args, **params)
      File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 553, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 962, in _make_api_call
        request_dict = self._convert_to_request_dict(
      File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 1036, in _convert_to_request_dict
        request_dict = self._serializer.serialize_to_request(
      File "/var/lang/lib/python3.11/site-packages/botocore/validate.py", line 381, in serialize_to_request
        raise ParamValidationError(report=report.generate_report())
    ```

2024-07-25 14:51 UTC, sh1un requested changes
錯誤已回報在上面的 Comment，需要先修復以上的錯誤

2024-07-27 19:19 UTC, sh1un commented
@Rich627 我目前實測下來後，業務邏輯似乎沒如期實現

## 問題回報

- 我把 `first_evaluated_key`，放入 queryParamString 裡面，無論如何都是返回第一頁，而非上一頁，而我後來檢查後，是程式碼內沒把 queryParam 所傳入的 `first_evaluated_key` 實作任何業務邏輯，因此相當於才會返回第一頁。
  - 預期行為是，我們會另外返回給前端另一個 `evaluated_key` 也就是你目前實作的 `first_evaluated_key`，這可以讓前端透過這個取得上一頁的內容
- 而我嘗試把 `first_evaluated_key`，放進去 `last_evaluated_key` 之後，會出現 500 Error，Logs 如下，會出現這個錯誤是因為你是把整個 file 的 item 拿去 encode 成 base64，而其中包含了浮點數 (file_size)：
  ```shell
  [ERROR] TypeError: Float types are not supported. Use Decimal types instead.
  Traceback (most recent call last):
    File "/var/task/lambda_function.py", line 103, in lambda_handler
      response = table.query(**query_kwargs)
    File "/var/lang/lib/python3.11/site-packages/boto3/resources/factory.py", line 581, in do_action
      response = action(self, *args, **kwargs)
    File "/var/lang/lib/python3.11/site-packages/boto3/resources/action.py", line 88, in __call__
      response = getattr(parent.meta.client, operation_name)(*args, **params)
    File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 553, in _api_call
      return self._make_api_call(operation_name, kwargs)
    File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 946, in _make_api_call
      api_params = self._emit_api_params(
    File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 1072, in _emit_api_params
      self.meta.events.emit(
    File "/var/lang/lib/python3.11/site-packages/botocore/hooks.py", line 412, in emit
      return self._emitter.emit(aliased_event_name, **kwargs)
    File "/var/lang/lib/python3.11/site-packages/botocore/hooks.py", line 256, in emit
      return self._emit(event_name, kwargs)
    File "/var/lang/lib/python3.11/site-packages/botocore/hooks.py", line 239, in _emit
      response = handler(**kwargs)
    File "/var/lang/lib/python3.11/site-packages/boto3/dynamodb/transform.py", line 217, in inject_attribute_value_input
      self._transformer.transform(
    File "/var/lang/lib/python3.11/site-packages/boto3/dynamodb/transform.py", line 289, in transform
      self._transform_parameters(model, params, transformation, target_shape)
    File "/var/lang/lib/python3.11/site-packages/boto3/dynamodb/transform.py", line 296, in _transform_parameters
      getattr(self, f'_transform_{type_name}')(
    File "/var/lang/lib/python3.11/site-packages/boto3/dynamodb/transform.py", line 312, in _transform_structure
      self._transform_parameters(
    File "/var/lang/lib/python3.11/site-packages/boto3/dynamodb/transform.py", line 296, in _transform_parameters
      getattr(self, f'_transform_{type_name}')(
    File "/var/lang/lib/python3.11/site-packages/boto3/dynamodb/transform.py", line 326, in _transform_map
      params[key] = transformation(value)
    File "/var/lang/lib/python3.11/site-packages/boto3/dynamodb/types.py", line 114, in serialize
      dynamodb_type = self._get_dynamodb_type(value)
    File "/var/lang/lib/python3.11/site-packages/boto3/dynamodb/types.py", line 127, in _get_dynamodb_type
      elif self._is_number(value):
    File "/var/lang/lib/python3.11/site-packages/boto3/dynamodb/types.py", line 171, in _is_number
      raise TypeError(
  ```
  <img width="1497" alt="image" src="https://github.com/user-attachments/assets/53882809-81e0-4760-822e-da38241323d1">


## 建議解決方式

首先務必要先了解 DynamoDB 的 LastEvaluatedKey 的運作原理，以下為推薦資源：

1. https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.Pagination.html
2. https://theburningmonk.com/2018/02/guys-were-doing-pagination-wrong/

接著，這是我建議的處理方式：

1. `first_evaluated_key` 建議更改為 -> `previous_last_evaluated_key`
1. 開給前端的 queryParam 給 `last_evaluated_key`，若前端想要查詢上一頁，前端應拿取 `previous_last_evaluated_key` 然後將其放入 queryParam - `last_evaluated_key` 來 call API

2024-07-27 19:22 UTC, sh1un requested changes

2024-07-27 19:22 UTC, sh1un commented on src/file_service/list_files/lambda_function.py
目前所實作的業務邏輯有誤喔，已將問題回報至上方 comment

2024-07-28 01:07 UTC, sh1un commented
@Rich627 
我幫你改好程式碼了，目前的雙向 pagination 業務邏輯已經實現，你可以幫我測測看

- 我有多加一個 table 是為了儲存某 user 的每次請求的 `evaluated_key`

關於程式碼的部分你會看到多了一些檔案，他們是以這樣的方式命名 `{table_name}_repository.py`

- 這是為了把對每個 dynamoDB table 的操作都抽離出來到這些檔案
- 會如此命名是因為參考了 [Python Repository Pattern](https://python.plainenglish.io/design-patterns-in-python-repository-pattern-1c2e5070a01c)，以及其他程式語言也有這種慣例 (Java / Go)

2024-07-28 04:29 UTC, Rich627 commented
@sh1un 大致上沒什麼問題, 但我發現到有一個小bug就是我如果往前一頁之後, 這時候的下一頁和前一頁好像都是統一導向到後面
你可以按照下面的步驟reproduce一下

重現步驟:
1. 先打一次
2. 拿到next_last_evaluated_key再打一次
3. 再拿nex_last_evaluated_key再打一次
4. 拿previos_last_evaluated_key打一次
5. 可以看到respose如下圖, previos和next是同一把key

預期行爲是key要有所不同

<img width="1394" alt="Screenshot 2024-07-28 at 12 16 47 PM" src="https://github.com/user-attachments/assets/b878939a-cd69-4ada-9462-705d3752d02b">

2024-07-28 11:59 UTC, sh1un commented
Hi @Rich627 
感謝回報，已修復 Bug，再麻煩你檢查一次看看

2024-07-28 15:16 UTC, merged