Scrum 18  api post send email
aws-educate-tw/aws-educate-tpet-backend pull request #6
Opened 2024-06-03 07:36 UTC by Rich627

2024-06-06 15:46 UTC, Rich627 commented
> Hi @Rich627 請串接 [Get file API](https://aws-educate-tw.postman.co/workspace/API-Development-Workspace~b6915213-64a3-408d-b297-45f472fa0a6b/request/35281217-5f372676-45da-4da5-96c7-7a7a36540395?action=share&source=copy-link&creator=35281217&ctx=documentation)，以透過此 API 來取得某 file 的 detail

Solved, plz review again

2024-06-06 17:07 UTC, sh1un requested changes

2024-06-06 17:07 UTC, sh1un commented on src/send-email/Dockerfile
> +CMD ["lambda_function.lambda_handler"]
這邊安裝 Dependency 的指令 `pip install` 放在後面，而主要執行的程式碼放前面，很可能會影響構建速度，因為你程式碼有改動，後面的 Layer 都要重 Build，建議將安裝 Dependency 的指令放在前面

相關文章:
 - [Docker Layer Cache](https://docs.docker.com/build/cache/)
 - [Docker Best Practices for Python Developers](https://testdriven.io/blog/docker-best-practices/#order-dockerfile-commands-appropriately)

    > Example:
    > 
    > FROM python:3.12.2-slim
    > 
    > WORKDIR /app
    > 
    > COPY sample.py .
    > 
    > COPY requirements.txt .
    > 
    > RUN pip install -r requirements.txt
    > In this Dockerfile, we copied over the application code before installing the requirements. Now, each time we change sample.py, the build will reinstall the packages. This is very inefficient, especially when using a Docker container as a development environment. Therefore, it's crucial to keep the files that frequently change towards the end of the Dockerfile.
    > 
    > You can also help prevent unwanted cache invalidations by using a .dockerignore file to exclude unnecessary files from being added to the Docker build context and the final image. More on this here shortly.
    > 
    > So, in the above Dockerfile, you should move the COPY sample.py . command to the bottom:
    > 
    > FROM python:3.12.2-slim
    > 
    > WORKDIR /app
    > 
    > COPY requirements.txt .
    > 
    > RUN pip install -r requirements.txt
    > 
    > COPY sample.py .

2024-06-07 15:40 UTC, sh1un requested changes

2024-06-07 15:40 UTC, sh1un commented on src/send-email/lambda_function.py
> +        logger.error(f"Error in excel column, can't find the match placeholder in template: {str(e)}")
Hi @Rich627 
這邊仍有一些地方使用到 f-string 來寫 log，須使用 %s 的方式

2024-06-07 15:40 UTC, sh1un commented on src/send-email/lambda_function.py
> +            logger.info(f"Email sent to {row.get('Name', 'Unknown')} at {formatted_send_time}")
Hi @Rich627 
同上~

2024-06-07 15:40 UTC, sh1un commented on src/send-email/lambda_function.py
> +            logger.error(f"Failed to send email to {row.get('Name', 'Unknown')}: {e}")
同上

2024-06-07 15:40 UTC, sh1un commented on src/send-email/lambda_function.py
> +        logger.error(f"Error in send_email: {str(e)}")
同上

2024-06-07 15:40 UTC, sh1un commented on src/send-email/lambda_function.py
> +        logger.error(f"Error saving to DynamoDB: {e}")
同上

2024-06-07 15:40 UTC, sh1un commented on src/send-email/lambda_function.py
> +        logger.error(f"Error in save_to_dynamodb: {str(e)}")
同上

2024-06-07 15:40 UTC, sh1un commented on src/send-email/lambda_function.py
> +        logger.warning(f"Invalid email format: {email}. Skipping...") # If email is invalid, skip sending
同上

2024-06-07 15:40 UTC, sh1un commented on src/send-email/lambda_function.py
> +            logger.error(f"Template validation error: Missing required columns for placeholders: {', '.join(missing_columns)}")
同上

2024-06-07 15:40 UTC, sh1un commented on src/send-email/lambda_function.py
> +        logger.info(f"Response: {response}")
同上

2024-06-07 15:40 UTC, sh1un commented on src/send-email/lambda_function.py
> +            logger.info(f"Response: {response}")
同上

2024-06-09 09:45 UTC, sh1un approved these changes
LGTM!

2024-06-09 09:45 UTC, merged